In [5]:
import numpy as np
a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
dir(a)


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

# Array Creation

In [16]:
import numpy as np
a1 = np.array([1,2,3])
print(type(a1))
print(a1)
a1


<class 'numpy.ndarray'>
[1 2 3]


array([1, 2, 3])

In [20]:
a1.dtype

dtype('int64')

In [24]:
b1 = np.array([1.1,1.2,1.3,1.4])
b1.dtype

dtype('float64')

In [29]:
#a2 = np.array(1,2,4,5) 
a2 = np.array([1,2,3,])
a2

array([1, 2, 3])

In [46]:
b2= np.array([(1,2,3,4,5),(5,4,3,2,1)])
b2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [49]:
print(b2.shape)
print(b2.size)

(2, 5)
10


In [51]:
b3 = np.array([[],[]])
b3

array([], shape=(2, 0), dtype=float64)

In [54]:
print(b3.shape)
print(b3.size)

(2, 0)
0


In [40]:
b3 = np.array([[1,2,3],[3,2,1]])
b3

array([[1, 2, 3],
       [3, 2, 1]])

In [64]:
print(b3.shape)
print(b3.size)
print(b3.ndim) # Return the number of dimensions of an array.
np.ndim(b3)


(2, 0)
0
2


2

In [75]:
b4= np.array([[1,1,2,4],[2,3,2,3],[3,4,2,3],[1,2,3,3]])
print(b4)
print(b4.ndim)
print(b4.itemsize)
print(type(b4))

[[1 1 2 4]
 [2 3 2 3]
 [3 4 2 3]
 [1 2 3 3]]
2
8
<class 'numpy.ndarray'>


In [78]:
c = np.array([[1,2],[1,1]], dtype=complex) #defined type of array explicitly
c

array([[ 1.+0.j,  2.+0.j],
       [ 1.+0.j,  1.+0.j]])

In [81]:
np.zeros((2,3))# function zeros creates full of zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [84]:
np.ones((4,4)) # function one creates full of ones

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [93]:

d = np.ones((2,2),dtype=np.int64) # specify dtype
d

array([[1, 1],
       [1, 1]])

In [99]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])